name: Deploy to Amazon Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Amazon Lightsail and pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: 3.148.55.185
          username: ubuntu
          key: ${{ secrets.OIDIVI_API_LIGHTSAIL_SSH_KEY }}
          script: |
            cd /var/www/oidivi-api

            # Configurar el directorio seguro para Git (opcional, pero recomendado)
            git config --global --add safe.directory /var/www/oidivi-api

            # Resetear el repositorio y traer los últimos cambios de la rama master
            git reset --hard
            git pull origin master

            # Restaurar los permisos adecuados (si es necesario, descomentar estas líneas)
            # sudo chown -R www-data:www-data storage bootstrap/cache
            # sudo chmod -R 775 storage bootstrap/cache

            # Reiniciar Apache, limpiar caché y ejecutar migraciones
            sudo systemctl restart apache2
            php artisan cache:clear
            php artisan config:clear
            php artisan view:clear
            php artisan route:clear

            php artisan migrate --force

            # Reiniciar Apache nuevamente si es necesario
            sudo systemctl restart apache2
